[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
ffi = false
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/contracts/=/Users/x/Desktop/polybets-monorepo/node_modules/@openzeppelin/contracts/",
    "@openzeppelin/=/Users/x/Desktop/polybets-monorepo/node_modules/@openzeppelin/"
]
